jQuery.noConflict();
jQuery(function(){var a=Math.floor(document.getElementById("prosperShopMain").offsetWidth-(document.getElementById("prosperFilterSidebar")?document.getElementById("prosperFilterSidebar").offsetWidth:0)-8),f=Math.ceil(a/250),b=Math.floor((a-8*f)/f);jQuery("#simProd.prosperResults").width(a);jQuery("#simProd.prosperResults li").width(b);jQuery("#simProd.prosperResults li img").css({height:b,width:b});jQuery("#simProd.prosperResults li .prosperLoad").css({height:b,width:b});jQuery("#simProd.prosperResults li").each(function(a){a+=1;
jQuery("#simProd.prosperResults li:nth-child("+a+")")[0]&&jQuery("#simProd.prosperResults li:nth-child("+a+") .prosperExtra").width(Math.floor(b-Math.ceil(jQuery("#simProd.prosperResults li:nth-child("+a+") .prosperPrice").width())-6))});jQuery("#simProd.prosperResults li").each(function(a){jQuery(this).attr("data-lirow",f+"-"+a)});(result=window.location.href.match(/cid\/(.{32})/))&&550<document.body.clientWidth&&prosperProdDetails("",result[1]);var c;jQuery(window).resize(function(){clearTimeout(c);
c=setTimeout(function(){var a=Math.floor(document.getElementById("prosperShopMain").offsetWidth-document.getElementById("prosperFilterSidebar").offsetWidth-8),b=Math.ceil(a/250),c=Math.floor((a-8*b)/b);jQuery("#simProd.prosperResults").width(a);jQuery("#simProd.prosperResults li").width(c);jQuery("#simProd.prosperResults li .prosperLoad").css({height:c,width:c});jQuery("#simProd.prosperResults ul li").each(function(a){a+=1;jQuery("#simProd.prosperResults li:nth-child("+a+")")[0]&&jQuery("#simProd.prosperResults li:nth-child("+
a+") .prosperExtra").width(Math.floor(c-Math.ceil(jQuery("#simProd.prosperResults li:nth-child("+a+") .prosperPrice").width())-6))});jQuery("#simProd.prosperResults li").each(function(a){jQuery(this).attr("data-lirow",b+"-"+a)})},200)})});
function toggle_visibility(a){a=document.getElementById(a);jQuery("#"+a.id).css("display","block"==jQuery("#"+a.id).css("display")?"none":"block");a.id+" fa fa-caret-down"==jQuery("i."+a.id).attr("class")?(jQuery("i."+a.id).removeClass("fa-caret-down"),jQuery("i."+a.id).addClass("fa-caret-up")):(jQuery("i."+a.id).removeClass("fa-caret-up"),jQuery("i."+a.id).addClass("fa-caret-down"))}
function prosperProdDetails(a,f){if(!_prosperShop.sdp){var b=jQuery("#"+a.id).attr("data-simresults");bodyWidth=jQuery("#prosperShopMain").width();resultWidth=bodyWidth-jQuery("#prosperFilterSidebar").width()-8;prodCount=Math.ceil(resultWidth/250);documentWidth=document.body.clientWidth;if(550>documentWidth)return b=jQuery("#"+a.id).attr("data-prosperKeyword"),window.location.href=window.location.protocol+"//"+window.location.hostname+"/product/"+b+"/cid/"+a.id,!1;if(b)var c=a.id.substr(3);else{window.parentId=
f?f:a.id;var c=parentId,e=jQuery("#"+c).attr("data-lirow");if(!jQuery("#"+c).attr("data-lirow"))return closeProsperDetails(),!1;b=e.match(/-(.*)/);e=e.match(/(.*)-/);b=parseInt(Math.floor(b[1]/e[1])*e[1])+prodCount;e=jQuery("*[data-lirow]").length;parent=c;jQuery(".prosperDetails").remove();jQuery(".prosperpointer").remove();jQuery("#simProd.prosperResults li:nth-child("+(e>b?b:e)+")").after('<li class="prosperDetails" style="overflow:hidden;"></li>');jQuery("#"+c).get(0).scrollIntoView({block:"start",
behavior:"smooth"})}jQuery.ajax({type:"POST",url:"http://api.prosperent.com/api/search",data:{api_key:_prosperShop.api,filterCatalogId:c,imageSize:"250x250",limit:1,imageMaskDomain:_prosperShop.imk,clickMaskDomain:_prosperShop.cmk,enableFullData:0},contentType:"application/json; charset=utf-8",dataType:"jsonp",timeout:500,success:function(a){b=window.location.href.replace(/\/$/,"");window.history.pushState("Test","",b.replace(/\/cid\/.{32}/,"")+"/cid/"+c+"/");jQuery("#prodbrand").empty();1==a.data.length?
jQuery.each(a.data,function(a,d){jQuery("meta[property=og\\:url]").attr("content",window.location.href);jQuery("meta[property=og\\:image]").attr("content",d.image_url.replace(/\/\/(.*?)\/images\/[0-9]{3,4}x[0-9]{3,4}/g,"//$1/images/600x315"));jQuery("meta[property=og\\:description]").attr("content",d.description);jQuery("meta[property=product\\:category]").attr("content",d.category);jQuery("meta[property=product\\:brand]").attr("content",d.brand);jQuery("meta[property=product\\:merchant]").attr("content",
d.merchant);jQuery("meta[property=og\\:title]").attr("content",d.keyword);jQuery("meta[property=product\\:price\\:amount]").attr("content",d.price);if(d.price_sale)if(document.querySelector("meta[property=product\\:sale_price\\:amount]"))jQuery("meta[property=product\\:sale_price\\:amount]").attr("content",d.price_sale);else{var b=document.createElement("meta");b.setAttribute("property","product\\:sale_price\\:amount");b.setAttribute("content",d.price_sale);document.getElementsByTagName("head")[0].appendChild(b)}document.querySelector("meta[name=twitter\\:card]")&&
document.querySelector("meta[name=twitter\\:site]")&&"summary_large_image"==document.querySelector("meta[name=twitter\\:card]").content&&(jQuery("meta[name=twitter\\:image]").attr("content",d.image_url.replace(/\/\/(.*?)\/images\/[0-9]{3,4}x[0-9]{3,4}/g,"//$1/images/512x256")),jQuery("meta[name=twitter\\:description]").attr("content",d.description),jQuery("meta[name=twitter\\:title]").attr("content",d.keyword));if(d.description){var c=d.description;250<c.length&&(b=c.substr(0,250),c=c.substr(249,
c.length-250),c=b+'<span class="moreellipses">... </span><span class="morecontent"><span>'+c+'</span><a href="javascript:void(0);" class="morelink" onClick="moreDesc(this);">More</a></span>')}var e=document.getElementById(parentId),b=jQuery(e).offset().left,f=jQuery("#simProd.prosperResults").offset().left,e=jQuery(e).outerWidth(!0),b=Math.floor(b-f+e/2-16)+"px";jQuery(".prosperDetails").html('<div><div class="prosperpointer" style="left:'+b+';height:14px;margin-top:10px;margin-bottom:-1px;position:relative;width:20px;z-index-1;"><img src="'+
_prosperShop.img+'/arrow.png"/></div><div class="prosperDetsContain"><div style="position:relative;padding:4px 4px 0 0;"><a href="javascript:void(0);" onClick="closeProsperDetails();"><i style="color:red;display:inline-block;float:right;font-size:16px;" class="fa fa-times"></i></a></div><div class="prosperDets"><div class="prosperDetContent"><div class="pDetailsImage"><a href="'+d.affiliate_url+'&interface=wp&subinterface=prospershop" target="_blank" rel="nofollow,nolink"><img src="'+d.image_url+
'" alt="'+d.keyword+'" title="'+d.keyword+'" /></a></div><div class="pDetailsAll"><div class="pDetailsKeyword"><a href="'+d.affiliate_url+'&interface=wp&subinterface=prospershop" target="_blank" rel="nofollow,nolink">'+d.keyword+'</a></div><div class="pDetailsDesc">'+c+'</div><table class="productResults"></table></div></div></div><div class="simTitle">Similar Products</div><div class="prosperSimResults" style="width:100%!important;max-width:100%!important;"><ul></ul></div></div></div>');jQuery.ajax({type:"POST",
url:"http://api.prosperent.com/api/search",data:{api_key:_prosperShop.api,filterProductId:d.productId,groupBy:"merchant",limit:10,enableFullData:0,imageMaskDomain:_prosperShop.imk,clickMaskDomain:_prosperShop.cmk,imageSize:"125x125"},contentType:"application/json; charset=utf-8",dataType:"jsonp",success:function(a){jQuery.each(a.data,function(a,b){jQuery(".productResults").append('<tr><td><img style="width:80px;height:40px;" src="http://images.prosperentcdn.com/images/logo/merchant/original/120x60/'+
b.merchantId+".jpg?prosp=&m="+b.merchant+'"/></td><td style="vertical-align:middle;"><strong>$'+(b.price_sale?b.price_sale:b.price)+'</strong></td><td style="vertical-align:middle;"><div class="shopCheck prosperVisit"><a itemprop="offerURL" href="'+b.affiliate_url+'&interface=wp&subinterface=prospershop" target="_blank" rel="nofollow,nolink"><input type="submit" type="submit" class="prosperVisitSubmit" value="'+(_prosperShop.vbt?_prosperShop.vbt:"Visit Store")+'"/></a></div></td></tr>')})},error:function(){console.log("here")}});
jQuery.ajax({type:"POST",url:"http://api.prosperent.com/api/search",data:{api_key:_prosperShop.api,query:d.keyword,limit:6,enableFullData:0,imageMaskDomain:_prosperShop.imk,clickMaskDomain:_prosperShop.cmk,imageSize:"125x125"},contentType:"application/json; charset=utf-8",dataType:"jsonp",success:function(a){var b=Math.floor(jQuery(".prosperSimResults")[0].getBoundingClientRect().width),c=Math.ceil(b/125),d=Math.floor((b-8*c)/c);0<a.data.length&&jQuery.each(a.data,function(a,b){jQuery(".prosperSimResults ul").append('<li data-simresults="1" id="sim'+
b.catalogId+'" class="'+b.productId+'" onClick="prosperProdDetails(this);" style="width:'+d+'px;cursor:pointer;"><div class="prodImage"><img src="'+b.image_url+'"/></div><div class="prodContent"><div class="prodTitle">'+(b.brand?b.brand:"&nbsp;")+"</div>$"+b.price+"</div></li>")})},error:function(){}})}):(jQuery(".prosperDetails").remove(),jQuery(".prosperpointer").remove())},error:function(){window.location.href=jQuery("#"+c+" .prodImage a").attr("href")}})}}
function closeProsperDetails(){jQuery(".prosperDetails").remove();var a=window.location.href.replace(/\/$/,"");window.history.pushState("RemovingCID","",a.replace(/\/cid\/.{32}/,""))}function moreDesc(a){jQuery(a).hasClass("less")?(jQuery(a).removeClass("less"),jQuery(a).html("More")):(jQuery(a).addClass("less"),jQuery(a).html("Less"));jQuery(a).parent().prev().toggle();jQuery(a).prev().toggle();return a};
